using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using DG.Tweening;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class PanelControllerNew : MonoBehaviour
{
    [Header("ï¿½pï¿½lï¿½ï¿½ï¿½ÌŠJï¿½Âï¿½ï¿½ï¿½")]
    public float animationTime = 0.3f;
    [Header("Windowï¿½Ìï¿½ï¿½Í‰ï¿½ï¿½ï¿½ï¿½Å•Â‚ï¿½ï¿½é‚©")]
    public bool canClose = true;
    [Header("Windowï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½")]
    public List<GameObject> windowOpener = new List<GameObject>();
    [Header("Windowï¿½ï¿½Â‚ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½")]
    public List<GameObject> windowCloser = new List<GameObject>();
    [Header("Windowï¿½ï¿½Â‚ï¿½ï¿½ï¿½wï¿½iï¿½{ï¿½^ï¿½ï¿½")]
    public GameObject backWindowCloser;
    [Header("Windowï¿½Ì”wï¿½i")]
    public GameObject backgroundPanel;
    [Header("Window")]
    public GameObject windowPanel;
    [Header("Windowï¿½Ìï¿½ï¿½vï¿½fï¿½Sï¿½ï¿½")]
    public GameObject panel;

    private RectTransform windowRect;
    private Vector3 defaultScale;
    private Image backImage;
    private bool isAnimate = false;

    private void Awake()
    {
        panel.SetActive(true);
    }

    // Start is called before the first frame update
    void Start()
    {
        windowRect = windowPanel.GetComponent<RectTransform>();
        defaultScale = windowRect.localScale;
        windowRect.localScale = Vector3.zero;

        backImage = backgroundPanel.GetComponent<Image>();
        backImage.color = Color.clear;

        // Windowï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ß‚Ìƒ{ï¿½^ï¿½ï¿½
        if (windowOpener != null)
        {
            foreach(GameObject g in windowOpener) g.GetComponent<Button>().onClick.AddListener(OpenPanel);
        }

        // Windowï¿½ï¿½Â‚ï¿½ï¿½é‚½ï¿½ß‚Ìƒ{ï¿½^ï¿½ï¿½
        if (windowCloser != null)
        {
            foreach (GameObject g in windowCloser) g.GetComponent<Button>().onClick.AddListener(ClosePanel);
        }

        // Windowï¿½ï¿½Â‚ï¿½ï¿½é‚½ï¿½ß‚Ì”wï¿½iï¿½{ï¿½^ï¿½ï¿½
        backWindowCloser.GetComponent<Button>().onClick.AddListener(() =>
        {
            if (canClose) { ClosePanel(); } else { DontClosePanel(); }
        });
        backWindowCloser.SetActive(false);
    }

    // Update is called once per frame
    void Update()
    {

    }

    /// <summary>
    /// Windowï¿½ï¿½ï¿½Jï¿½ï¿½
    /// </summary>
    public void OpenPanel()
    {
        backWindowCloser.SetActive(true);
        isAnimate = true;
        windowRect.DOScale(defaultScale, animationTime).SetEase(Ease.OutBack);
        backImage.DOFade(0.8f, animationTime).OnComplete(() => isAnimate = false);
    }

    /// <summary>
    /// Windowï¿½ï¿½Â‚ï¿½ï¿½ï¿½
    /// </summary>
    public void ClosePanel()
    {
        backWindowCloser.SetActive(false);
        isAnimate = true;
        windowRect.DOScale(0, animationTime).SetEase(Ease.InBack);
        backImage.DOFade(0, animationTime).OnComplete(() => isAnimate = false);
    }

    /// <summary>
    /// Windowï¿½ï¿½Â‚ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½Æ‚ğ‘£‚ï¿½
    /// </summary>
    public void DontClosePanel()
    {
        windowRect.DOPunchScale(Vector3.one * 0.05f, animationTime).OnComplete(() => windowRect.DOScale(Vector3.one, 0.001f));
    }
}
